format = """
[î‚¶](#776B5D)\
$username\
[î‚´](bg:#B0A695 fg:#776B5D)\
$directory\
[î‚´](fg:#B0A695 bg:#776B5D)\
$git_branch\
$git_status\
[î‚´](fg:#776B5D bg:#B0A695)\
$c\
$golang\
$java\
$rust\
[î‚´](fg:#B0A695)\
$status\
$fill\
[î‚¶](fg:#6f618b fg:#6f618b)\
$cmd_duration\
[î‚´](fg:#6f618b fg:#6f618b)
[â†ª ](fg:#33658A)\
"""
# #AFD787
# #DA627D
# #9A348E
# #BEC6A0
# #9BB0C1
# #6f618b
# #B0A695

# Disable the blank line at the start of the prompt
add_newline = false

[fill]
symbol = " "
#style = "bg:#6f618b"
disabled = false

[cmd_duration]
min_time = 1
style = "bg:#6f618b fg:#ffffff"
format = '[$duration]($style)'
#show_notifications = true
show_milliseconds = true
#min_time_to_notify = 1

[status]
style = "bold fg:red"
symbol = "ğŸ”´"
success_symbol = ""
#format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
format = "[ $symbol Exit code: $status]($style)"
map_symbol = true
disabled = false

[line_break]
disabled = true


# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bold bg:#776B5D fg:#ffffff"
style_root = "bg:#9A348E fg:#AAF27D"
format = '[$user]($style)'

[directory]
style = "bg:#B0A695"
read_only = ""
format = "[ $path ]($style)"
truncation_symbol = "â€¦/"
truncation_length = 80
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = "ï˜"
style = "bg:#776B5D fg:#ffffff"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#776B5D fg:#ffffff"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#B0A695"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#B0A695"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A fg:white"
format = '[ â™¥ $time ]($style)'
